baseURL = "https://as204994.net/"
languageCode = "en-us"
title = "AS204994"
theme = "mainroad"
googleAnalytics = "UA-220614-24"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Blog Posts"
weight = -9
identifier = "blogposts"
url = "/post"

[params.copyright]
prefix = ""
holder = "Tiernan OToole"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)


disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Network info for AS204994"
title404 = "Nothing's here!"


# About Widget config
[about]
title = ""                            # default: .Site.Title
description = ""                      # default: .Site.Params.info.description
logo = "/images/logo.png"             # default: "/images/logo.png"

# Recent Posts Widget config
[recent_posts]
title = ""                            # default: "Recent Posts"
length = 4                            # default: 5
excludeTypes = ["page"]               # default: ["page"]

# Search Widget config
[search]
title = "Search"                      # default: "Search"

# Sidebar Menu Widget config
[sidebar_menu]
title = ""                            # default: ""
mirror = ""                           # default: ""

# Social Menu Widget config
[social_menu]
title = ""                            # default: ""
platforms = ["github","facebook","twitter","instagram","email","codepen","gitlab","linkedin","telegram","google_scholar","youtube"]

# Taxonomy Cloud Widget config
[taxonomy_cloud]
title = ""                            # default: Plural Name for `taxonomyCloud.taxonomy`
taxonomy = "tags"                     # default: "tags"
shuffle = true                        # default: true